# Generated by Django 2.1.5 on 2019-01-26 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Incompatible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Side_Effects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_effect', models.CharField(max_length=30)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorrecords.Medication')),
            ],
        ),
        migrations.CreateModel(
            name='System_Affected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=30)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorrecords.Condition')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorrecords.Prompt')),
            ],
        ),
        migrations.AddField(
            model_name='incompatible',
            name='medication_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorrecords.Medication'),
        ),
        migrations.AddField(
            model_name='condition',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorrecords.Medication'),
        ),
        migrations.AddField(
            model_name='condition',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorrecords.Prompt'),
        ),
        migrations.AddField(
            model_name='client',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorrecords.Condition'),
        ),
    ]
