# Generated by Django 2.1.5 on 2019-01-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorrecords', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Patient',
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name_plural': 'Condition'},
        ),
        migrations.AlterModelOptions(
            name='hcp',
            options={'verbose_name_plural': 'HCP'},
        ),
        migrations.AlterModelOptions(
            name='incompatible',
            options={'verbose_name_plural': 'Incompatible'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name_plural': 'Medication'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'Patient'},
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={'verbose_name_plural': 'Prompt'},
        ),
        migrations.AlterModelOptions(
            name='side_effects',
            options={'verbose_name_plural': 'Side_Effects'},
        ),
        migrations.AlterModelOptions(
            name='system_affected',
            options={'verbose_name_plural': 'System Affected'},
        ),
        migrations.RenameField(
            model_name='incompatible',
            old_name='medication_1',
            new_name='medication',
        ),
    ]
