# Generated by Django 2.1.5 on 2019-01-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorrecords', '0002_auto_20190126_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='system_affected',
            name='prompt',
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
    ]
