# Generated by Django 2.1.5 on 2019-01-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorrecords', '0003_auto_20190126_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
