# Generated by Django 2.1.5 on 2019-01-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorrecords', '0007_auto_20190126_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.AddField(
            model_name='hcp',
            name='employee_number',
            field=models.IntegerField(default=123333, unique=True),
            preserve_default=False,
        ),
    ]
