# Generated by Django 2.1.5 on 2019-01-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorrecords', '0008_auto_20190127_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name_plural': 'Health Conditions'},
        ),
        migrations.AlterModelOptions(
            name='hcp',
            options={'verbose_name_plural': 'Healthcare Providers'},
        ),
        migrations.AlterModelOptions(
            name='incompatible',
            options={'verbose_name_plural': 'Incompatabilities'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name_plural': 'Medications'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='side_effects',
            options={'verbose_name_plural': 'Side Effects'},
        ),
        migrations.AlterModelOptions(
            name='system_affected',
            options={'verbose_name_plural': 'Systems Affected'},
        ),
        migrations.AddField(
            model_name='patient',
            name='addr_line_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='addr_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='healthcard_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True),
        ),
    ]
