# Generated by Django 2.1.5 on 2019-01-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorrecords', '0009_auto_20190126_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
