# Generated by Django 2.1.5 on 2019-01-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorrecords', '0010_patient_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.CharField(blank=True, choices=[('Heart Disease', 'Heart Disease - Father'), ('Diabetes', 'Diabetes - Grandmother'), ('Alzheimers', 'Alzheimers - Mother'), ('High Blood Pressure', 'High Blood Pressure - Grandfather'), ('Arthritis', 'Arthritis - Mother'), ('Obesity', 'Obesity - Father'), ('Cancer', 'Cancer - Sister'), ('High Cholesterol', 'High Cholesterol - Sister'), ('Asthma', 'Asthma - Brother')], max_length=100, null=True),
        ),
    ]
