# Generated by Django 2.1.5 on 2019-01-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorrecords', '0011_patient_family_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medication',
            field=models.ManyToManyField(blank=True, null=True, to='doctorrecords.Medication'),
        ),
    ]
