# Generated by Django 2.1.5 on 2019-01-27 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorrecords', '0012_auto_20190127_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('treatment_start_date', models.DateField(blank=True, null=True)),
                ('treatment_renewal_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Active Conditions',
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Conditions',
            },
        ),
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_member', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Grandfather', 'Grandfather'), ('Grandmother', 'Grandmother'), ('Sibling', 'Sibling')], max_length=100)),
                ('condition', models.ManyToManyField(to='doctorrecords.Conditions')),
            ],
        ),
        migrations.CreateModel(
            name='HealthcareProviders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.IntegerField(unique=True)),
                ('name_title', models.CharField(default='Dr.', max_length=5)),
                ('name_first', models.CharField(blank=True, max_length=30, null=True)),
                ('name_last', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Healthcare Providers',
            },
        ),
        migrations.CreateModel(
            name='SideEffects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('new', models.BooleanField(default=False)),
                ('side_effects', models.ManyToManyField(blank=True, null=True, to='doctorrecords.SideEffects')),
            ],
            options={
                'verbose_name_plural': 'Treatments',
            },
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='medication',
        ),
        migrations.DeleteModel(
            name='Incompatible',
        ),
        migrations.RemoveField(
            model_name='side_effects',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='system_affected',
            name='condition',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='addr_line_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='addr_line_2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='family_history',
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medication',
            field=models.ManyToManyField(blank=True, null=True, to='doctorrecords.Treatments'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='HCP',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='Side_Effects',
        ),
        migrations.DeleteModel(
            name='System_Affected',
        ),
        migrations.AddField(
            model_name='conditions',
            name='side_effects',
            field=models.ManyToManyField(blank=True, null=True, to='doctorrecords.SideEffects'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='treatments',
            field=models.ManyToManyField(to='doctorrecords.Treatments'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='healthcare_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctorrecords.HealthcareProviders'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorrecords.Patient'),
        ),
        migrations.AddField(
            model_name='activeconditions',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorrecords.Conditions'),
        ),
        migrations.AddField(
            model_name='activeconditions',
            name='treatment',
            field=models.ManyToManyField(blank=True, null=True, to='doctorrecords.Treatments'),
        ),
        migrations.AddField(
            model_name='patient',
            name='active_conditions',
            field=models.ManyToManyField(to='doctorrecords.ActiveConditions'),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.ManyToManyField(to='doctorrecords.FamilyHistory'),
        ),
    ]
