# Generated by Django 2.1.5 on 2019-01-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorrecords', '0013_auto_20190127_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcareproviders',
            old_name='name_first',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='healthcareproviders',
            old_name='name_last',
            new_name='last_name',
        ),
    ]
