# Generated by Django 2.1.5 on 2019-01-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorrecords', '0014_auto_20190127_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incompatibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incompat_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctorrecords.Conditions')),
                ('incompat_treatments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_compared_to', to='doctorrecords.Treatments')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_queried', to='doctorrecords.Treatments')),
            ],
            options={
                'verbose_name_plural': 'Incompatabilities',
            },
        ),
    ]
